version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: forzy_postgres
    restart: always
    environment:
      POSTGRES_USER: forzy
      POSTGRES_PASSWORD: forzy123
      POSTGRES_DB: forzy_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
