-- 006_motor_segmento.sql
-- Catálogo dos 23 segmentos do modelo 3D (public/3d/Engine1.obj) do motor WEG
-- W22 3cv monofásico, carcaça 100L. Fonte única de verdade para o que hoje
-- vive duplicado em forzy-web/src/config/motorParts.ts e
-- forzy-api/rag_module/tools/motor_parts_tool.py — os dois arquivos passam a
-- ser gerados/sincronizados a partir desta tabela, não editados à mão.
--
-- Dados transcritos de motorParts.ts (fonte mais completa, com `inspecao`).
-- Identificação dos segmentos por geometria do OBJ (mm, escala 1:1), não por
-- inspeção visual — ver comentário original em motorParts.ts.

CREATE TABLE IF NOT EXISTS motor_segmento (
    id                   TEXT PRIMARY KEY,              -- nome do objeto no OBJ (empty_2..empty_24)
    label                TEXT NOT NULL,                  -- nome oficial WEG da peça
    grupo_funcional      TEXT NOT NULL                   -- mecanico | eletrico | termico | estrutural | vedacao
                             CHECK (grupo_funcional IN ('mecanico','eletrico','termico','estrutural','vedacao')),
    descricao            TEXT NOT NULL,
    sinal_velocidade     TEXT NOT NULL DEFAULT 'nenhuma'
                             CHECK (sinal_velocidade IN ('forte','media','fraca','nenhuma')),
    sinal_aceleracao     TEXT NOT NULL DEFAULT 'nenhuma'
                             CHECK (sinal_aceleracao IN ('forte','media','fraca','nenhuma')),
    sinal_temperatura    TEXT NOT NULL DEFAULT 'nenhuma'
                             CHECK (sinal_temperatura IN ('forte','media','fraca','nenhuma')),
    componentes_internos JSONB NOT NULL DEFAULT '[]',    -- string[] — peças sem malha própria representadas por esta
    modos_falha          JSONB NOT NULL DEFAULT '[]',    -- [{nome, assinatura, precocidade}]
    destacavel           BOOLEAN NOT NULL DEFAULT false, -- pode acender vermelho no diagnóstico
    inspecao             TEXT,                           -- o que o manual WEG manda inspecionar (§8.1)
    atualizado_em        TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO motor_segmento
    (id, label, grupo_funcional, descricao, sinal_velocidade, sinal_aceleracao, sinal_temperatura,
     componentes_internos, modos_falha, destacavel, inspecao)
VALUES
('empty_2', 'Carcaça', 'termico', 'Corpo do motor, com as aletas de refrigeração e os pés de fixação B3D. Aloja o estator bobinado e é a principal superfície de troca de calor com o ambiente.', 'media', 'fraca', 'forte', '["Estator bobinado", "Núcleo do estator", "Isolamento classe F", "Pés de fixação", "Placa de identificação"]'::jsonb, '[{"nome": "Sobreaquecimento do enrolamento", "assinatura": "Temperatura sobe de forma sustentada com a vibração praticamente inalterada.", "precocidade": "tardio"}, {"nome": "Dissipação prejudicada por sujeira", "assinatura": "Temperatura sobe gradualmente ao longo de dias, sem mudança no padrão de vibração.", "precocidade": "precoce"}, {"nome": "Fixação frouxa / ressonância da base", "assinatura": "Vibração aumenta em picos intermitentes, com o nível médio ainda normal.", "precocidade": "precoce"}]'::jsonb, true, 'Manter a carcaça limpa: acúmulo de óleo ou pó na parte externa prejudica a troca de calor. Verificar o aperto dos parafusos de sustentação e fixação.'),
('empty_7', 'Tampa dianteira (lado acionado)', 'mecanico', 'Fecha o motor do lado da ponta do eixo e aloja o rolamento dianteiro. Mantém o alinhamento entre rotor e estator, e é onde a norma manda medir vibração.', 'forte', 'forte', 'media', '["Rolamento dianteiro 6206", "Vedação V-Ring dianteira", "Arruela ondulada", "Alojamento do mancal"]'::jsonb, '[{"nome": "Rolamento desgastado", "assinatura": "Aceleração sobe com picos curtos de alta energia, elevando o fator de crest antes do valor eficaz. Temperatura do mancal acompanha depois.", "precocidade": "precoce"}, {"nome": "Lubrificação inadequada", "assinatura": "Temperatura do mancal sobe junto com a aceleração; ruído aumenta.", "precocidade": "tardio"}, {"nome": "Desalinhamento do acoplamento", "assinatura": "Velocidade de vibração sobe de forma sustentada, concentrada em 1× a rotação.", "precocidade": "tardio"}]'::jsonb, true, 'Verificar o estado dos mancais observando ruídos e níveis de vibração não habituais, a temperatura do mancal e a condição do lubrificante. Relubrificação a cada 25.000 h (5 g).'),
('empty_13', 'Tampa traseira (lado não acionado)', 'mecanico', 'Fecha o motor do lado do ventilador e aloja o rolamento traseiro. É também a peça externa que cobre o mecanismo de partida do motor monofásico.', 'media', 'forte', 'media', '["Rolamento traseiro 6206", "Vedação V-Ring traseira", "Centrífugo (mecanismo de partida)", "Platinado"]'::jsonb, '[{"nome": "Rolamento traseiro desgastado", "assinatura": "Aceleração sobe com fator de crest crescente; velocidade quase inalterada no início.", "precocidade": "precoce"}, {"nome": "Falha do mecanismo centrífugo de partida", "assinatura": "Comportamento anormal só durante a partida: o motor demora a atingir a rotação e aquece mais que o normal nos primeiros minutos.", "precocidade": "precoce"}]'::jsonb, true, 'Mesmo procedimento do mancal dianteiro. Em motor monofásico, verificar também se o mecanismo de partida desarma corretamente ao atingir a rotação.'),
('empty_19', 'Tampa defletora', 'termico', 'Capa que protege o ventilador e direciona o ar sobre as aletas da carcaça. Na refrigeração IC411 o ventilador é acoplado ao próprio eixo, então parado o motor, para a ventilação.', 'fraca', 'fraca', 'forte', '["Ventilador", "Grelha de entrada de ar", "Fluxo de ar IC411"]'::jsonb, '[{"nome": "Ventilação obstruída", "assinatura": "Temperatura sobe de forma sustentada com velocidade e aceleração normais. É a causa número um de sobretemperatura segundo o manual WEG.", "precocidade": "precoce"}, {"nome": "Ventilador danificado ou desbalanceado", "assinatura": "Aceleração sobe moderadamente e a temperatura acompanha, por perda de refrigeração.", "precocidade": "tardio"}]'::jsonb, true, 'Verificar a condição do ventilador e das entradas e saídas de ar, assegurando livre fluxo. Respeitar as distâncias mínimas entre a entrada da defletora e paredes próximas.'),
('empty_23', 'Eixo', 'mecanico', 'Transmite o torque do rotor para a máquina acionada. Diâmetro escalonado Ø30 no assento do rolamento e Ø28 na ponta livre. É o proxy visível do rotor, que não tem malha própria.', 'forte', 'media', 'fraca', '["Rotor (gaiola)", "Núcleo do rotor", "Assento do rolamento"]'::jsonb, '[{"nome": "Desbalanceamento do rotor", "assinatura": "Velocidade de vibração sobe de forma sustentada e proporcional à rotação, com a aceleração subindo menos que a velocidade.", "precocidade": "tardio"}, {"nome": "Eixo empenado ou desalinhado", "assinatura": "Vibração oscila periodicamente acompanhando a rotação; temperatura sobe por consequência.", "precocidade": "tardio"}]'::jsonb, true, 'Inspeção visual do acoplamento observando alinhamento, sinais de desgaste e peças danificadas.'),
('empty_4', 'Caixa de ligação', 'eletrico', 'Aloja a placa de bornes, o aterramento e os capacitores. Em motor monofásico ela é grande justamente porque precisa acomodar os capacitores de partida e permanente.', 'fraca', 'fraca', 'media', '["Capacitor de partida", "Capacitor permanente", "Placa de bornes", "Aterramento", "Prensa-cabos"]'::jsonb, '[{"nome": "Capacitor degradado", "assinatura": "O motor demora a atingir a rotação nominal e aquece mais que o normal, com a vibração pouco alterada.", "precocidade": "tardio"}, {"nome": "Conexão frouxa ou mau contato", "assinatura": "Temperatura sobe sem causa mecânica aparente; vibração permanece normal.", "precocidade": "tardio"}]'::jsonb, true, 'Verificar a conexão dos cabos de alimentação, o aperto dos parafusos de conexão, o estado da passagem dos cabos e as vedações dos prensa-cabos.'),
('empty_6', 'Tampa da caixa de ligação', 'eletrico', 'Chapa externa com o logo WEG em relevo, que fecha a caixa de ligação e garante o IP55. É a peça mais externa do modelo.', 'nenhuma', 'nenhuma', 'fraca', '[]'::jsonb, '[]'::jsonb, false, 'Verificar as vedações da caixa de ligação e efetuar a troca se necessário.'),
('empty_5', 'Junta da tampa da caixa de ligação', 'vedacao', 'Lâmina de vedação entre a caixa de ligação e sua tampa. Garante o grau de proteção IP55.', 'nenhuma', 'nenhuma', 'nenhuma', '[]'::jsonb, '[]'::jsonb, false, 'Verificar o estado das vedações e efetuar a troca se necessário.'),
('empty_3', 'Olhal de içamento', 'estrutural', 'Ponto de suspensão para transporte e instalação do motor. Não participa da operação.', 'nenhuma', 'nenhuma', 'nenhuma', '[]'::jsonb, '[]'::jsonb, false, NULL),
('empty_24', 'Chaveta', 'mecanico', 'Peça de 8×7 mm alojada no rasgo do eixo, que transmite o torque para o elemento acoplado. Dimensão normalizada DIN 6885 para eixo Ø28–30.', 'fraca', 'media', 'nenhuma', '[]'::jsonb, '[{"nome": "Folga ou desgaste da chaveta", "assinatura": "Aceleração sobe em impactos intermitentes; velocidade média permanece normal.", "precocidade": "precoce"}]'::jsonb, false, 'O manual alerta que balanceamento diferente entre motor e acoplamento (meia chaveta vs. chaveta inteira) causa ruído e vibração — exige refazer o balanceamento.'),
('empty_9', 'Dreno (tampa dianteira)', 'vedacao', 'Permite escoar condensado acumulado no interior do motor, preservando o IP55.', 'nenhuma', 'nenhuma', 'nenhuma', '[]'::jsonb, '[]'::jsonb, false, 'Drenar o motor e recolocar os drenos para garantir o grau de proteção. Devem ficar posicionados de forma que a drenagem seja facilitada.'),
('empty_18', 'Dreno (tampa traseira)', 'vedacao', 'Dreno do lado não acionado. Mesma função do dreno dianteiro.', 'nenhuma', 'nenhuma', 'nenhuma', '[]'::jsonb, '[]'::jsonb, false, 'Drenar e recolocar para garantir o IP55.'),
('empty_8', 'Parafuso de fixação (tampa dianteira)', 'estrutural', 'Prende a tampa dianteira à carcaça. Soltura dos parafusos é causa reconhecida de ruído e vibração elevada, mas nenhum sinal que medimos isola um parafuso específico.', 'fraca', 'fraca', 'nenhuma', '[]'::jsonb, '[]'::jsonb, false, 'Verificar se o aperto dos parafusos de conexão, sustentação e fixação está conforme a Tabela 8.16 do manual WEG.'),
('empty_10', 'Parafuso de fixação (tampa dianteira)', 'estrutural', 'Prende a tampa dianteira à carcaça. Soltura dos parafusos é causa reconhecida de ruído e vibração elevada, mas nenhum sinal que medimos isola um parafuso específico.', 'fraca', 'fraca', 'nenhuma', '[]'::jsonb, '[]'::jsonb, false, 'Verificar se o aperto dos parafusos de conexão, sustentação e fixação está conforme a Tabela 8.16 do manual WEG.'),
('empty_11', 'Parafuso de fixação (tampa dianteira)', 'estrutural', 'Prende a tampa dianteira à carcaça. Soltura dos parafusos é causa reconhecida de ruído e vibração elevada, mas nenhum sinal que medimos isola um parafuso específico.', 'fraca', 'fraca', 'nenhuma', '[]'::jsonb, '[]'::jsonb, false, 'Verificar se o aperto dos parafusos de conexão, sustentação e fixação está conforme a Tabela 8.16 do manual WEG.'),
('empty_12', 'Parafuso de fixação (tampa dianteira)', 'estrutural', 'Prende a tampa dianteira à carcaça. Soltura dos parafusos é causa reconhecida de ruído e vibração elevada, mas nenhum sinal que medimos isola um parafuso específico.', 'fraca', 'fraca', 'nenhuma', '[]'::jsonb, '[]'::jsonb, false, 'Verificar se o aperto dos parafusos de conexão, sustentação e fixação está conforme a Tabela 8.16 do manual WEG.'),
('empty_14', 'Parafuso de fixação (tampa traseira)', 'estrutural', 'Prende a tampa traseira à carcaça. Soltura dos parafusos é causa reconhecida de ruído e vibração elevada, mas nenhum sinal que medimos isola um parafuso específico.', 'fraca', 'fraca', 'nenhuma', '[]'::jsonb, '[]'::jsonb, false, 'Verificar se o aperto dos parafusos de conexão, sustentação e fixação está conforme a Tabela 8.16 do manual WEG.'),
('empty_15', 'Parafuso de fixação (tampa traseira)', 'estrutural', 'Prende a tampa traseira à carcaça. Soltura dos parafusos é causa reconhecida de ruído e vibração elevada, mas nenhum sinal que medimos isola um parafuso específico.', 'fraca', 'fraca', 'nenhuma', '[]'::jsonb, '[]'::jsonb, false, 'Verificar se o aperto dos parafusos de conexão, sustentação e fixação está conforme a Tabela 8.16 do manual WEG.'),
('empty_16', 'Parafuso de fixação (tampa traseira)', 'estrutural', 'Prende a tampa traseira à carcaça. Soltura dos parafusos é causa reconhecida de ruído e vibração elevada, mas nenhum sinal que medimos isola um parafuso específico.', 'fraca', 'fraca', 'nenhuma', '[]'::jsonb, '[]'::jsonb, false, 'Verificar se o aperto dos parafusos de conexão, sustentação e fixação está conforme a Tabela 8.16 do manual WEG.'),
('empty_17', 'Parafuso de fixação (tampa traseira)', 'estrutural', 'Prende a tampa traseira à carcaça. Soltura dos parafusos é causa reconhecida de ruído e vibração elevada, mas nenhum sinal que medimos isola um parafuso específico.', 'fraca', 'fraca', 'nenhuma', '[]'::jsonb, '[]'::jsonb, false, 'Verificar se o aperto dos parafusos de conexão, sustentação e fixação está conforme a Tabela 8.16 do manual WEG.'),
('empty_20', 'Parafuso de fixação (tampa defletora)', 'estrutural', 'Prende a tampa defletora à carcaça. Soltura dos parafusos é causa reconhecida de ruído e vibração elevada, mas nenhum sinal que medimos isola um parafuso específico.', 'fraca', 'fraca', 'nenhuma', '[]'::jsonb, '[]'::jsonb, false, 'Verificar se o aperto dos parafusos de conexão, sustentação e fixação está conforme a Tabela 8.16 do manual WEG.'),
('empty_21', 'Parafuso de fixação (tampa defletora)', 'estrutural', 'Prende a tampa defletora à carcaça. Soltura dos parafusos é causa reconhecida de ruído e vibração elevada, mas nenhum sinal que medimos isola um parafuso específico.', 'fraca', 'fraca', 'nenhuma', '[]'::jsonb, '[]'::jsonb, false, 'Verificar se o aperto dos parafusos de conexão, sustentação e fixação está conforme a Tabela 8.16 do manual WEG.'),
('empty_22', 'Parafuso de fixação (tampa defletora)', 'estrutural', 'Prende a tampa defletora à carcaça. Soltura dos parafusos é causa reconhecida de ruído e vibração elevada, mas nenhum sinal que medimos isola um parafuso específico.', 'fraca', 'fraca', 'nenhuma', '[]'::jsonb, '[]'::jsonb, false, 'Verificar se o aperto dos parafusos de conexão, sustentação e fixação está conforme a Tabela 8.16 do manual WEG.')
ON CONFLICT (id) DO UPDATE SET
    label                = EXCLUDED.label,
    grupo_funcional       = EXCLUDED.grupo_funcional,
    descricao            = EXCLUDED.descricao,
    sinal_velocidade     = EXCLUDED.sinal_velocidade,
    sinal_aceleracao     = EXCLUDED.sinal_aceleracao,
    sinal_temperatura    = EXCLUDED.sinal_temperatura,
    componentes_internos = EXCLUDED.componentes_internos,
    modos_falha          = EXCLUDED.modos_falha,
    destacavel           = EXCLUDED.destacavel,
    inspecao             = EXCLUDED.inspecao,
    atualizado_em        = now();
